backend:
  name: github
  branch: master
  repo: mykytav/gatsby-blog-experiment

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "Posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Categories", name: "categories", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: true }
      - { label: "Author", name: "author", widget: hidden, default: Mykyta Vlasov }
      - { label: "Type", name: "type", widget: hidden, default: post }
      - { label: "Body", name: "body", widget: "markdown" }
